# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbUbwbmj0SE0HVOHRnuFZ0jwe9H8SUk0
"""

!pip freeze > requirements.txt

